# Generated by Django 4.0 on 2021-12-10 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionDetail', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentName', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='approvalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvalDetail', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Contact', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=150)),
                ('Region', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='listTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hobbies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='productType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNumber', models.CharField(max_length=150, unique=True)),
                ('Address', models.TextField()),
                ('Region', models.CharField(max_length=150)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmanagesystem.productname')),
                ('custContact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custno', to='cmanagesystem.customer')),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmanagesystem.customer')),
                ('itemType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmanagesystem.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('action', models.TextField()),
                ('approval', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmanagesystem.agent')),
                ('cContact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customerContact', to='cmanagesystem.product')),
                ('callNature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmanagesystem.producttype')),
                ('serialNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmanagesystem.product')),
            ],
        ),
    ]
