# Generated by Django 4.0 on 2021-12-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmanagesystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='cContact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmanagesystem.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='custContact',
            field=models.CharField(max_length=20),
        ),
    ]
