# Generated by Django 4.0 on 2021-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmanagesystem', '0002_alter_call_ccontact_alter_product_custcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=150),
        ),
    ]
