# Generated by Django 4.0 on 2021-12-10 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmanagesystem', '0004_alter_call_ccontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmanagesystem.productname'),
        ),
    ]
