# Generated by Django 4.0 on 2021-12-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmanagesystem', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customerName',
            field=models.CharField(max_length=150),
        ),
    ]
