# Generated by Django 4.0 on 2021-12-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmanagesystem', '0007_alter_call_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='serialNumber',
            new_name='srNumber',
        ),
    ]
