# Generated by Django 4.0 on 2021-12-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmanagesystem', '0008_rename_serialnumber_call_srnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serialNumber',
            field=models.CharField(max_length=150),
        ),
    ]
