# Generated by Django 4.0 on 2021-12-11 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmanagesystem', '0009_alter_product_serialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
